#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

BLOXROUTE_CLIENT_PORT=12345

cd src/client
./build.sh
cd -
docker run -t -v $DIR/../src/bxgateway:/app -p $BLOXROUTE_CLIENT_PORT:$BLOXROUTE_CLIENT_PORT bxgateway $*
